name: goodwishes
description: Goodwishes Project App

version: 0.0.5+5

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #apple_sign_in: ^0.1.0
  sign_in_with_apple: ^3.3.0
  audio_service: ^0.18.2
  audio_session: ^0.1.6+1
  audio_video_progress_bar: ^0.10.0
  awesome_circular_chart: ^1.0.0
  badges: ^2.0.2
  cached_network_image: ^3.2.0
  connectivity: ^3.0.6
  cloud_firestore: ^3.1.4
  cupertino_icons: ^1.0.4
  datetime_picker_formfield: ^2.0.0 
  dio: ^4.0.4
  equatable: ^2.0.3
  file_picker: ^4.2.7
  firebase_analytics: ^9.0.3
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  firebase_crashlytics: ^2.4.3
  firebase_dynamic_links: ^4.0.2
  firebase_messaging: ^11.2.3
  firebase_storage: ^10.2.3
  flutter_login_facebook: ^1.2.0
  flutter_local_notifications: ^9.1.5
  flutter_native_timezone: ^2.0.0
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^7.2.0
  flutter_html: ^2.0.0-nullsafety.0
  flutter_modular: ^4.2.0
  flutter_mobx: ^2.0.2
  flutter_picker: ^2.0.2
  flutter_staggered_animations: ^1.0.0
  flutter_widget_from_html: ^0.8.2
  global_configuration: 2.0.0-nullsafety.1
  get_it: ^7.2.0
  google_sign_in: ^5.2.1
  google_fonts: ^2.1.0
  just_audio: ^0.9.18
  image_picker: ^0.8.4+4
  in_app_review: ^2.0.3
  intl: ^0.17.0 
  introduction_screen: ^2.1.0
  mobx: ^2.0.5
  package_info: ^2.0.2
  path_provider: ^2.0.8
  simple_animations: ^4.0.1
  shared_preferences: ^2.0.9
  share: ^2.0.4
  supercharged: ^2.1.1
  skeleton_text: ^3.0.0
  syncfusion_flutter_charts: ^19.3.57
  timezone: ^0.8.0
  fluttertoast: ^8.0.8
  image_cropper: ^1.4.1
  font_awesome_flutter: ^9.2.0
  youtube_player_flutter: ^8.0.0
  url_launcher: ^6.0.17
  webview_flutter: ^2.8.0

dev_dependencies:
  build_runner: ^2.1.5
  mobx_codegen: ^2.0.4
  pedantic: ^1.11.1
  flutter_launcher_icons: ^0.9.2
  
dependency_overrides:

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/logo_goodwishes.png"
  image_path_ios: "assets/images/logo_goodwishes.png"    


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/social-icon/
    - assets/images/icon/
    - assets/cfg/
    - assets/sounds/background/
    - assets/sounds/gongo/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic    
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-BoldItalic.ttf
          weight: 700
          style: italic          
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
